client localhost {
    ipaddr = 127.0.0.1
    secret = testing123
    shortname = localhost
    require_message_authenticator = no
}

client localhost_ipv6 {
    ipv6addr = ::1
    secret = testing123
    shortname = localhost6
    require_message_authenticator = no
}

# عميل واحد فقط لكل الشبكات (MikroTik + Backend + أي جهاز)
client all_networks {
    ipaddr = 0.0.0.0/0
    secret = testing123
    shortname = all
    require_message_authenticator = no
    nas_type = other
}